# Generated by Django 3.2.16 on 2023-01-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0173_oauthauthorizationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthauthorizationcode',
            name='code_challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oauthauthorizationcode',
            name='code_challenge_method',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oauthauthorizationcode',
            name='state',
            field=models.TextField(blank=True),
        ),
    ]
