# Generated by Django 3.2.16 on 2023-01-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0174_auto_20230112_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthauthorizationcode',
            name='code_challenge',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oauthauthorizationcode',
            name='code_challenge_method',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oauthauthorizationcode',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
