# Generated by Django 3.2.16 on 2023-01-12 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0175_auto_20230112_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthBearerToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('client_id', models.TextField()),
                ('scope', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
