""" creating new permission that allows managing book data in the admin settings """
# Generated by Django 3.2.16 on 2023-01-26 10:41

from django.db import migrations


def create_perms(apps, schema_editor):
    """create the new" "moderate_book_data" permission"""
    db_alias = schema_editor.connection.alias
    group_model = apps.get_model("auth", "Group")

    # Create perms, if needed
    user_model = apps.get_model("bookwyrm", "User")
    content_type_model = apps.get_model("contenttypes", "ContentType")
    content_type = content_type_model.objects.get_for_model(user_model)
    perms_model = apps.get_model("auth", "Permission")
    reg_perm, perm_created = perms_model.objects.using(db_alias).get_or_create(
        codename="moderate_book_data",
        name="moderate book data",
        content_type=content_type,
    )

    # Add perms to the group if anything was created
    if perm_created:
        owner_group, _ = group_model.objects.using(db_alias).get_or_create(name="owner")
        owner_group.permissions.add(reg_perm)

        admin_group, _ = group_model.objects.using(db_alias).get_or_create(name="admin")
        admin_group.permissions.add(reg_perm)


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0176_mergedauthor"),
    ]

    operations = [migrations.RunPython(create_perms, migrations.RunPython.noop)]
