# Generated by Django 3.2.16 on 2023-01-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0173_default_user_auth_group_setting'),
        ('bookwyrm', '0176_oauthbearertoken'),
        ('bookwyrm', '0177_create_moderate_book_data_permission'),
    ]

    operations = [
    ]
